### ISSUE TITLE
ISO C forbids braced-groups within expressions

### ISSUE THREAD

**Issue by lbolla** [stephenmathieson/assertion-macros.h#2]
All macros seem defined wrapping code blocks in (), e.g. https://github.com/stephenmathieson/assertion-macros.h/blob/master/assertion-macros.h#L51

This causes gcc and clang to complain because "ISO C forbids braced-groups within expressions".

Instead, why not remove the () or use "do {...} while(0)", like done elsewhere (e.g.https://github.com/antirez/redis/blob/unstable/src/server.h#L481)?

**Comment by stephenmathieson** [comment]
done, thanks :)
